config/routes.rb
ImgurClone::Application.routes.draw do
  root :to => 'sessions#new'
  
  get "auth/facebook/callback" => "sessions#create"
  
  resources :home, only: [:index]

  resources :users, only: [:new, :create] do
    resources :photos, only: [:create]
    
    resources :regions, only: [:index, :new, :create]

    member do
      get "favorites"
      get "uploaded_images"
    end
  end

  resource :session, only: [:new, :create, :destroy]

  resources :photos, only: [:index, :show, :update, :destroy] do
    resources :comments,  only: [:create, :index] 
    resources :user_votes, only: [:index]
    resources :favorites, only: [:create]

    member do
      post "upvote"
      post "downvote"
      post "cancelvote"
    end
  end

  resources :regions, only: [:show, :edit, :update, :destroy]
  resources :comments,  only: [:destroy]
  resources :favorites, only: [:destroy]

  resource :password_reset, only: [:new, :create, :edit, :update]

end

app/views/headers/_portal.html.erb
<header>
  <nav class="portal">

    <div id="portal_buttons">
      <div>
        <a href="<%= root_url %>"><p>Login</p></a>
			</div>
			<div>
        <a href="<%= new_user_url %>"><p>Sign Up</p></a>
			</div>
    </div>

  </nav>
</header>

app/views/headers/_signed_in.html.erb
<header>
  <nav class="signed_in">
    <div id="home_link">
      <a href="<%= photos_url %>"><p>imgUm</p></a>
    </div>

    <div id="nav_buttons">
      <div id="image_upload">
        <a href="<%= new_user_photo_url(self.current_user.id) %>"><p>Upload Image</p></a>
      </div>

      <div id="username">
        <p><%= self.current_user.username %></p>
        <ul id="username_dropdown">
          <li><%= link_to "My Favorites", favorites_user_url(self.current_user.id) %></li>
          <li><%= link_to "My Images", uploaded_images_user_url(self.current_user.id) %></li>
          <li><%= link_to "My Regions", user_regions_url(self.current_user.id) %></li>
          <li><%= button_to "Logout", session_url, method: :delete %></li>
        </ul>
      </div>


    </div>

  </nav>
</header>