config/routes.rb
ImgurClone::Application.routes.draw do
  root :to => 'sessions#new'
  
  get "auth/facebook/callback" => "sessions#create"
  
  resources :home, only: [:index]

  resources :users, only: [:new, :create] do
    resources :photos, only: [:create]
    
    resources :regions, only: [:index, :new, :create]

    member do
      get "favorites"
      get "uploaded_images"
    end
  end

  resource :session, only: [:new, :create, :destroy]

  resources :photos, only: [:index, :show, :update, :destroy] do
    resources :comments,  only: [:create, :index] 
    resources :user_votes, only: [:index]
    resources :favorites, only: [:create]

    member do
      post "upvote"
      post "downvote"
      post "cancelvote"
    end
  end

  resources :regions, only: [:show, :edit, :update, :destroy]
  resources :comments,  only: [:destroy]
  resources :favorites, only: [:destroy]

  resource :password_reset, only: [:new, :create, :edit, :update]

end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :name, :user_id, :north_bound, :south_bound, :east_bound, :west_bound
  
  validates :name, :user_id, :north_bound, :south_bound, :east_bound, :west_bound, presence: true
  
  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
  
  def find_in_region_photos
    # lat_range = ((self.latitude - 0.003)..(self.latitude + 0.003))
    # long_range = ((self.longitude - 0.003)..(self.longitude + 0.003))
    # photos_in_range = Photo.where(latitude: lat_range).where(longitude: long_range)
  end
  
  def markers_string
    markers_str = ""
    markers = ("A".."Z").to_a
    photos = self.find_in_region_photos
    
    photos.each_with_index do |photo, index| 
      markers_str = markers_str + "|label, {markers[index]}|#{photo.latitude}, #{photo.longitude}|,"
    end
    markers_str[0,(markers_str.length-1)]
  end
  
  def static_page
    url = Addressable::URI.new(
        :scheme => "https",
        :host => "maps.googleapis.com",
        :path => "/maps/api/staticmap",
        :query_values => {
          :center => "#{self.latitude},#{self.longitude}",
          :zoom => 18,
          :markers => "#{self.markers_string}",
          :size => "500x400",
          :sensor => "false"
        }).to_s
  end
  
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  respond_to :json
  
  def index
    @regions = self.current_user.regions
  end
  
  
  def create
    @region = Region.new(params[:region])
    @region.user_id = self.current_user.id
    
    if @region.save
      respond_with @region
    else
      flash[:errors] = @region.errors.full_messages
      respond_with @region
    end
    
  end
  
  
  def destroy
    @region = Region.find(params[:id])
    @region.destroy
    
    redirect_to user_regions_url(self.current_user)
  end
  
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/index.html.erb
<h1>My Regions</h1>

<%= link_to "Add a Region", new_user_region_url %>

<% @regions.each do |region| %>
	<p><%= link_to region.name, region_url(region.id) %></p>
<% end %>

app/views/regions/new.html.erb
<h1>Add a Region</h1>

<form action="<%= user_regions_url(self.current_user.id) %>" method="post">
  <input type="hidden"
         name="authenticity_token"
        value="<%= form_authenticity_token %>">
				
	<input type="text" name="region[name]" placeholder="Region Name">
	
	<input type="text" name="region[latitude]" placeholder="Latitude">
	
	<input type="text" name="region[longitude]" placeholder="Longitude">

	<input type="submit" value="Add Region">
	
</form>

app/views/regions/show.html.erb
<section class="my_regions">
	<%= button_to "Delete Region", region_url(@region.id), method: :delete %>
	
	<h1><%= @region.name %></h1>
	
	<div class="region_images">	
		<% @region.find_in_region_photos.each do |photo| %>
			<div class="region_images_index">
				<a href="/photos/<%= photo.id %>"><img src="<%= photo.image.url %>"></a>
			</div>
		<% end %>
	</div>
	
	<div class="region_map">
		<img src="<%= @region.static_page %>"></a>
	<div>
	
	
</section>